Update README.md
JuulLabs-OSS/kotlin-guides pull request #1
Opened 2018-05-14 21:33 UTC by nachtien

Let's use snake case instead of camelcase for xml variables.

2018-05-14 21:34 UTC, nachtien commented
@TravisJuul @casey-juul @JuulLabs/juul-eng-app

2018-05-15 01:34 UTC, ebabel commented on README.md
> +import kotlinx.android.synthetic.main.scan.login as login_view
I was thinking we'd always use at least one `_` in the xml

2018-05-15 01:35 UTC, ebabel reviewed
I was thinking we'd always use at least one `_` in the xml. But w/e

2018-05-15 03:30 UTC, nachtien commented
@ebabel Travis and I talked about the case where there might (hopefully never) be where a view wouldn't be snake cased, so we came up with a use case for that.  How do you feel about postfixing `_view` to the end of those properties

2018-05-15 03:36 UTC, TravisJuul commented on README.md
> +import kotlinx.android.synthetic.main.scan.login as login_view
I think one of the benefits of going with the XML name is that we no longer have to go through the trouble of specifying `as` for the `import`.

So perhaps the requirement for having an `_` should be for the XML `id`?

2018-05-15 07:18 UTC, casey-juul reviewed
Me being difficult on purpose aside, I really do feel like adding "_view" solely for the purpose of reinforcing the underbar decision is hacky. But this is also super low priority in the grand scheme of things, so whatever you guys decide is fine.

2018-05-15 07:18 UTC, casey-juul commented on README.md
> +properties that do not have an underscore in their name, and append `_view` to the end
@TravisJuul I thought you kinda agree with me on this one... or at least cringed  😛 

Either you should go with all views having "_<type>" or none. This feels like a hack :)

2018-05-15 18:15 UTC, ebabel requested changes

2018-05-15 18:15 UTC, ebabel commented on README.md
>  When using [Kotlin Android Extensions] to provide synthetic view properties, use the `as` keyword on [imports] to name
take out `as`

2018-06-01 08:34 UTC, TravisJuul commented
I personally like using the XML ID in code (i.e. with underscores), but playing devil's advocate: lint complains about underscores:

![screen shot 2018-05-31 at 1 43 18 pm](https://user-images.githubusercontent.com/29553341/40830555-986c36e4-653b-11e8-9f7a-694a082a147f.png)

Although the lint only seems to catch the variables that came in from `findViewById`, but shows that we would be violating a standard in Android if we when with the underscore in variable name approach.

2018-10-30 04:26 UTC, twyatt commented
Bump. I think we should merge this, as establishing this as a standard would be helpful, and we can hopefully later look into disabling the lint check.

> I really do feel like adding "_view" solely for the purpose of reinforcing the underbar decision is hacky

I agree with @casey-juul, although I think the rule of omitting `_view` postfix should be a recommendation (not a requirement). In most cases coming up with a 2 word description of a component should be pretty easy. In instances were it proves difficult, then as a last resort it should be fine to postfix the name with the component type (e.g. `_button` or `_view`).

If others agree, then maybe we should add a little more detail to the `README.md` changes in this PR?

2018-12-06 18:59 UTC, twyatt commented
We agreed in-person that https://github.com/JuulLabs-OSS/kotlin-guides/pull/1#issuecomment-434167788 is a good approach. @nachtien, can you update the PR verbiage accordingly?

2018-12-06 19:00 UTC, ebabel commented
I'm cool with either, slight preference for the '_hacky_' "adding "_view" solely for the purpose of reinforcing the underbar decision"

2018-12-06 19:11 UTC, twyatt requested changes

2018-12-06 19:11 UTC, twyatt commented on README.md
> +View ID names (`android:id` in XML) should be all lowercase with underscores separating words (snake_case).  It is required that every name will have at least one underscore that way it is distinguis
```suggestion
View ID names (`android:id` in XML) should be all lowercase with underscores separating words (snake_case). It is required that every name have at least one underscore to distinguish it from local variables. In instances were it proves difficult, then name may be postfixed with the component type (e.g. `_button` or `_view`).
```

2018-12-06 19:15 UTC, twyatt approved these changes

2018-12-06 19:15 UTC, merged